import { Inter } from "next/font/google";
import "./globals.css";
import { BookingProvider } from "../contexts/BookingContext";
import ReviewComponent from "../components/common/ReviewComponent";
import {
  getSetup,
  getAvailabilityForDateRangeV2,
  getAvailabilitySearch,
} from "../serverMethods/servermethods";
import { NavigationProvider } from "../contexts/NavigationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Resdiary Booking Widget",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentDate = new Date();

  const setup = await getSetup(currentDate.toISOString().split("T")[0]);
  const availabilityForDateRangeV2 = await getAvailabilityForDateRangeV2(
    currentDate,
    setup.OnlinePartySizeDefault
  );
  const availabilitySearch = await getAvailabilitySearch(
    setup.OnlinePartySizeDefault,
    currentDate
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <BookingProvider
          setup={setup}
          availabilitySearch={availabilitySearch}
          availabilityForDateRangeV2={availabilityForDateRangeV2}
        >
          {/* <div className="flex flex-col items-center justify-center min-h-full px-4 py-6 overflow-hidden bg-white rounded-md shadow-lg max-w-lg mx-auto my-10 sm:min-h-screen">
            <div className="w-full max-w-3xl px-4 py-5 sm:p-6 lg:px-8"> */}
          <div className="flex flex-col items-center justify-center min-h-screen bg-gray-50">
            <div className="bg-white rounded-lg shadow-xl overflow-hidden max-w-screen-md w-full mx-4 md:mx-0 my-10">
              <ReviewComponent />
              <div className="p-4 space-y-4">
                <NavigationProvider>{children}</NavigationProvider>
              </div>
            </div>
          </div>
        </BookingProvider>
      </body>
    </html>
  );
}
