import { Inter } from "next/font/google";
import "./globals.css";
import { BookingProvider } from "../contexts/BookingContext";
import {
  getSetup,
  getAvailabilityForDateRangeV2,
  getAvailabilitySearch,
} from "../serverMethods/servermethods";
import { NavigationProvider } from "../contexts/NavigationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Resdiary Booking Widget",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentDate = new Date();

  const setup = await getSetup(currentDate.toISOString().split("T")[0]);
  const availabilityForDateRangeV2 = await getAvailabilityForDateRangeV2(
    currentDate,
    setup.OnlinePartySizeDefault
  );
  const availabilitySearch = await getAvailabilitySearch(
    setup.OnlinePartySizeDefault,
    currentDate
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <NavigationProvider>
          <BookingProvider
            setup={setup}
            availabilitySearch={availabilitySearch}
            availabilityForDateRangeV2={availabilityForDateRangeV2}
          >
            {/* <div className=" flex flex-col border-2 border-black  items-center justify-center ">
              <div className="bg-white rounded-lg border-2 border-black shadow-lg overflow-hidden max-w-screen-md w-full mx-2 md:mx-0 my-10">
                <div className="border-b-2 border-black ">
                  <ReviewComponent />
                </div> */}
            <div className="p-4 space-y-4 ">{children}</div>
            {/* </div>
            </div> */}
          </BookingProvider>
        </NavigationProvider>
      </body>
    </html>
  );
}

{
  /* <div className="border-4 border-red-500"> */
}
